---
galaxy_info:
  role_name: common
  author: shubham-singh
  description: Base system setup for Twenty CRM EC2
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
dependencies: []
