apiVersion: v1
kind: Secret
metadata:
  name: twenty-secrets
  namespace: twenty
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: default
  PG_DATABASE_URL: postgres://postgres:postgres@twenty-postgres:5432/default
  APP_SECRET: "a1234567890b1234567890c1234567890d1234567890"