aws_region           = "us-east-1"
instance_name        = "twenty-crm-task14"
instance_type        = "t3.small"
ami_id               = "ami-0b6d9d3d33ba97d99"
key_name             = "task-10-purva"
ssh_allowed_cidr     = "0.0.0.0/0"
crm_allowed_cidr     = "0.0.0.0/0"
iam_instance_profile = "EC2S3AccessRole"

ecr_repository_name = "twenty-crm"
s3_bucket_name      = "twenty-crm-task14-purva"
