---
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/shubhamsingh-task17.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: /usr/bin/python3

  children:
    crm_servers:
      hosts:
        shubham-task17:
          ansible_host: 13.201.88.57
