region               = "us-east-1"
ami_id               = "ami-0c02fb55956c7d316"
instance_type        = "t3.small"
key_name             = "shradha-task12-new-key"
iam_instance_profile = "EC2ECRPullRole"
ecr_repository_name  = "twenty-crm"
s3_bucket_name       = "twenty-crm-task14-shradha"
