apiVersion: v1
kind: Service
metadata:
  name: twenty-crm-service
  namespace: devops-crm
spec:
  type: NodePort
  selector:
    app: twenty-crm
  ports:
    - port: 2020
      targetPort: 2020
      nodePort: 30020